using System.Collections.Generic;
using UnityEngine;

namespace PoingMort.Traffic
{
    /// <summary>
    /// Closed lane authored in the scene (points in world space). Generated by the scene builder,
    /// editable in the Inspector; the yellow gizmo shows the path and its direction.
    /// </summary>
    public sealed class TrafficLane : MonoBehaviour
    {
        [Tooltip("Points du circuit, dans l'ordre de circulation (boucle fermée).")]
        public List<Vector3> points = new List<Vector3>();
        [Tooltip("Voie voisine à gauche, même sens de circulation (optionnel).")]
        public TrafficLane leftNeighbour;
        [Tooltip("Voie voisine à droite, même sens de circulation (optionnel).")]
        public TrafficLane rightNeighbour;
        [Tooltip("Voie côté trottoir : la sortie de voiture se fait de préférence de ce côté.")]
        public bool kerbOnRight = true;

        LaneLoop m_Loop;

        public LaneLoop Loop
        {
            get
            {
                if (m_Loop == null && points != null && points.Count >= 3)
                    m_Loop = new LaneLoop(points);
                return m_Loop;
            }
        }

        public void Invalidate() => m_Loop = null;

        void OnValidate() => m_Loop = null;

        void OnDrawGizmos()
        {
            if (points == null || points.Count < 2) return;
            Gizmos.color = new Color(1f, 0.8f, 0.1f, 0.9f);
            for (int i = 0; i < points.Count; i++)
            {
                Vector3 a = points[i] + Vector3.up * 0.1f;
                Vector3 b = points[(i + 1) % points.Count] + Vector3.up * 0.1f;
                Gizmos.DrawLine(a, b);
                if (i % 6 == 0)
                {
                    Vector3 dir = (b - a).normalized;
                    Vector3 side = Vector3.Cross(Vector3.up, dir) * 0.6f;
                    Gizmos.DrawLine(b, b - dir * 1.2f + side);
                    Gizmos.DrawLine(b, b - dir * 1.2f - side);
                }
            }
        }
    }
}
