using UnityEngine;
using UnityEngine.SceneManagement;

namespace PoingMort.Core
{
    /// <summary>Scene names and transitions. Both scenes are generated by PoingMort &gt; Construire les scènes.</summary>
    public static class SceneFlow
    {
        public const string MainMenuScene = "MainMenu";
        public const string GameScene = "Quartier";

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
        static void Boot()
        {
            GameSettings.Load();
            Time.timeScale = 1f;
            AudioListener.pause = false;
        }

        public static void LoadMainMenu() => Load(MainMenuScene);
        public static void LoadGame() => Load(GameScene);

        static void Load(string scene)
        {
            Time.timeScale = 1f;
            AudioListener.pause = false;
            if (!Application.CanStreamedLevelBeLoaded(scene))
            {
                Debug.LogError($"[PoingMort] La scène « {scene} » n'est pas dans les Build Settings. " +
                               "Lance le menu PoingMort > 2. Construire les scènes.");
                return;
            }
            SceneManager.LoadScene(scene);
        }

        public static void Quit()
        {
#if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
#else
            Application.Quit();
#endif
        }
    }
}
